### ISSUE TITLE
AREL代码问题

### ISSUE THREAD

**Issue by xinli2008** [antct/blog#5]
您好，我看到了您在AREL代码下面的问题评论，我想请问，那个问题你解决了吗？
因为我也遇到了差不多同样的问题，很遗憾的是，我能力不足，花了很多时间还没想出来。
如果可以，我们可以交流一下吗？
https://github.com/eric-xw/AREL/issues/12
如有打扰，还请海涵。

**Comment by antct** [comment]
您好~
我当时尝试了这个修改之后就成功了~
id2word[str(vocab_id)] 改为 id2word[str(int(vocab_id))]
这个好久之前了，具体也不太记得了，可能也会有一些torch版本的问题

**Comment by sudalixin** [comment]
您好，您在哪里修改的这个啊。我怎么没找到您说的这个啊。
祝好

**Comment by antct** [comment]
File "/data/lihaozheng/AREL/misc/utils.py", line 59, in decode_story
    txt = txt + ' ' + id2word[str(vocab_id)]

路径AREL/misc/utils.py，应该就是对应这个，你可以找找~


少年啊 <notifications@github.com> 于2020年12月13日周日 上午12:21写道：

**Comment by xinli2008** [comment]
您好，我现在基本可以确定我的问题了，可能是缺少lib32stdc++6这个库，
因为您的服务器跑起来了这个代码，所以我想让您帮我看一下您的服务器有没有这个库。
可以用dpkg -l查看服务器所有的库，然后在人为查看有没有这个库。
如果有这个库，应该就是这个库的问题。如果没有这个库的话，那就是其他的问题。谢谢！

**Comment by antct** [comment]
> 您好，我现在基本可以确定我的问题了，可能是缺少lib32stdc++6这个库，
> 因为您的服务器跑起来了这个代码，所以我想让您帮我看一下您的服务器有没有这个库。
> 可以用dpkg -l查看服务器所有的库，然后在人为查看有没有这个库。
> 如果有这个库，应该就是这个库的问题。如果没有这个库的话，那就是其他的问题。谢谢！

这个可能暂时查看不了，因为以前是一年前的了，服务器环境有很大的变化。
我记得当时应该只是这个bug，按照我上述的修改应该就可以了。如果你确实lib依赖，用conda安装环境也许可以解决~

**Comment by xinli2008** [comment]
好吧，很可惜。这个包必须用sudo来安装，conda无法安装，很可惜。
您是专门研究visual storytelling方向的吗？



在 2020-12-14 20:31:21，"tt" <notifications@github.com> 写道：

您好，我现在基本可以确定我的问题了，可能是缺少lib32stdc++6这个库，
因为您的服务器跑起来了这个代码，所以我想让您帮我看一下您的服务器有没有这个库。
可以用dpkg -l查看服务器所有的库，然后在人为查看有没有这个库。
如果有这个库，应该就是这个库的问题。如果没有这个库的话，那就是其他的问题。谢谢！

这个可能暂时查看不了，因为以前是一年前的了，服务器环境有很大的变化。
我记得当时应该只是这个bug，按照我上述的修改应该就可以了。如果你确实lib依赖，用conda安装环境也许可以解决~

**Comment by antct** [comment]
> 好吧，很可惜。这个包必须用sudo来安装，conda无法安装，很可惜。 您是专门研究visual storytelling方向的吗？ 在 2020-12-14 20:31:21，"tt" <notifications@github.com> 写道： 您好，我现在基本可以确定我的问题了，可能是缺少lib32stdc++6这个库， 因为您的服务器跑起来了这个代码，所以我想让您帮我看一下您的服务器有没有这个库。 可以用dpkg -l查看服务器所有的库，然后在人为查看有没有这个库。 如果有这个库，应该就是这个库的问题。如果没有这个库的话，那就是其他的问题。谢谢！ 这个可能暂时查看不了，因为以前是一年前的了，服务器环境有很大的变化。 我记得当时应该只是这个bug，按照我上述的修改应该就可以了。如果你确实lib依赖，用conda安装环境也许可以解决~ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有没有，只是去年的时候了解过这个任务~
